version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: hw6_postgres
    environment:
      POSTGRES_USER: p_user
      POSTGRES_PASSWORD: p_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./product_data.csv:/docker-entrypoint-initdb.d/product_data.csv
volumes:
  postgres-data:
